alias exa="exa --icons --header --git"
alias ls="exa -G"
alias la="exa -a"
alias ll="exa -l"
alias lt="exa -T"
alias g="git"
alias vi="nvim"
alias vim="nvim"

export EDITOR="nvim"
export VISUAL="nvim"
export TERM="xterm-256color"
